service: trece-alexa-skill

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-west-1
  memorySize: 128
  timeout: 5
  environment:
    ALEXA_SKILL_ID: amzn1.ask.skill.4f5658c4-2045-48ff-b14f-0a2250bbd677

functions:
  trece:
    handler: index.handler
    name: ${self:service}-${self:provider.stage}
    events:
      - alexaSkill: ${self:provider.environment.ALEXA_SKILL_ID}
